### ISSUE TITLE
Login form problem if prepopulated by browser

### ISSUE THREAD

**Issue by Alexander-Kreutz** [28msec/nolap-report-editor#19]
The login form is automatically filled with my username and password by the browser. If the form is submitted I get an error message saying that both username and password are not filled out.

**Comment by wcandillon** [comment]
Assigning @dknochen

**Comment by wcandillon** [comment]
@Alexander-Kreutz this issue is presumably fixed in `cellfire`. Can you confirm?

@dknochen Can you explain me what the fix does?

**Comment by dknochen** [comment]
@wcandillon its not yet fixed, its only prepared to be fixed ;). I need to talk to you about it tomorrow.
